$(function(){
  var users=[
    
    {
      name:'王勇浩',
      img:'../images/studentsImg/001.png',
      yx:'郑州大学（8队）',
      zy:'计算机网络安全',
      jy:'上海晓联信息技术有限公司',
      zw:'Web前端开发工程师',
      xz:' 10300+五险一金'
    },
    {
      name:'周明航',
      img:'../images/studentsImg/002.png',
      yx:'郑州大学（7队）',
      zy:'计算机科学与技术',
      jy:'上海宝信软件股份有限公司',
      zw:'Web前端开发工程师',
      xz:'10000+五险一金'
    },
    {
      name:'赵少坤',
      img:'../images/studentsImg/003.png',
      yx:'郑州大学（9队）',
      zy:'计算机程序编译',
      jy:'文思海辉技术有限公司',
      zw:'Web前端开发工程师',
      xz:'8000+五险一金'
    },
    {
      name:'孙建',
      img:'../images/studentsImg/004.png',
      yx:'郑州大学（9队）',
      zy:'计算机程序编译',
      jy:'上海亿顺和信息科技有限公司',
      zw:'Java开发工程师',
      xz:'8000+五险一金'
    },
    {
      name:'陈创',
      img:'../images/studentsImg/005.png',
      yx:'郑州大学（8队）',
      zy:'计算机网络安全',
      jy:'上海英和文化传播有限公司',
      zw:'8000+五险一金+13薪',
      xz:''
    },
    {
      name:'王敬霖',
      img:'../images/studentsImg/006.png',
      yx:'郑州大学（9队）',
      zy:'计算机程序编译',
      jy:'上海新意新科技有限公司',
      zw:'Java开发工程师',
      xz:'8000+五险一金'
    },
    {
      name:'王春晓',
      img:'../images/studentsImg/007.png',
      yx:'郑州大学（9队）',
      zy:'计算机程序编译',
      jy:'无锡智道安盈科技有限公司',
      zw:'Java开发工程师',
      xz:'8000+五险一金'
    },
    {
      name:'罗皓',
      img:'../images/studentsImg/008.png',
      yx:'郑州大学（9队）',
      zy:'计算机程序编译',
      jy:'上海云贝网络科技有限公司',
      zw:'Java开发工程师',
      xz:'7500+五险一金'
    },
    {
      name:'孙勇',
      img:'../images/studentsImg/009.png',
      yx:'郑州大学（9队）',
      zy:'计算机程序编译',
      jy:'上海灵萃信息科技公司',
      zw:'Java开发工程师',
      xz:'8000+五险一金'
    },
    {
      name:'郭文舟',
      img:'../images/studentsImg/010.png',
      yx:'郑州大学（9队）',
      zy:'程序设计与编译',
      jy:'奔驰集团河南分公司',
      zw:'Java开发工程师',
      xz:'6000+五险一金+三餐'
    },
    {
      name:'吴召',
      img:'../images/studentsImg/011.png',
      yx:'郑州大学（7队）',
      zy:'程序设计与编译',
      jy:'郑州中移在线服务有限公司',
      zw:'Java开发工程师',
      xz:'7.4万+五险一金'
    },
    {
      name:'钱超亚',
      img:'../images/studentsImg/012.png',
      yx:'郑州大学（9队）',
      zy:'计算机程序编译',
      jy:'上海宏恒软件有限公司',
      zw:'Web前端开发工程师',
      xz:'8000+五险一金'
    },
    {
      name:'陈金龙',
      img:'../images/studentsImg/013.png',
      yx:'郑州大学（7队）',
      zy:'计算机科学与技术',
      jy:'苏州市伏泰信息科技股份有限公司',
      zw:'web前端工程师',
      xz:'10000+五险一金'
    },
    {
      name:'常斌',
      img:'../images/studentsImg/014.png',
      yx:'郑州大学（7队）',
      zy:'计算机科学与技术',
      jy:'中移在线服务有限公司',
      zw:'web前端工程师',
      xz:'年薪7.4万+五险一金'
    },
    {
      name:'曹坤',
      img:'../images/studentsImg/015.png',
      yx:'华北水利水电大学',
      zy:'土木工程',
      jy:'深圳市思源计算机软件有限公司',
      zw:'web前端工程师',
      xz:'10000+五险一金'
    },
    {
      name:'郝天旺',
      img:'../images/studentsImg/016.png',
      yx:'河南工业大学',
      zy:'生物工程',
      jy:'文思海辉技术有限公司',
      zw:'Web前端开发工程师',
      xz:'9500+五险一金'
    }
  ],i;
  for(i=0;i<users.length;i++){
    $('.studentList .row')
    .append(
      $('<div class="every col-xs-12 col-sm-12 col-md-6 "></div>')
      .append($('<div></div>')
        .append($('<i><span>优秀学员</span></i>'))
        .append($('<b></b>'))
        .append($('<s></s>'))
        .append($('<span></span>'))
        .append($('<img src="'+users[i].img+'" alt="">'))
        .append($('<span class="name">'+users[i].name+'</span>'))
        .append($('<p></p>')
          .html(
            '毕业院校'+users[i].yx+
            '<br>专业'+users[i].zy+
            '<br>就业公司'+users[i].jy+
            '<br>职位'+users[i].zw+
            '<br>薪资'+users[i].xz))
        )
      );
  }
});
